# _config.yml
#layouts_dir     : ./_sharedTemplates/_layouts
includes_dir     : ./_includes
encoding: UTF-8
theme: jekyll-theme-slate
title: Trackmatic Technical Integration Guide

docs_list_title: Integrations Documentation
docs:

- title: Introduction
  url: test2/introduction.md

- title: Configuration
  url: test2/configuration.md

- title: Deployment
  url: test2/deployment.md

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"