# _config.yml
#layouts_dir     : ./_sharedTemplates/_layouts
includes_dir     : ./_includes
encoding: UTF-8
theme: jekyll-theme-slate
title: Trackmatic Technical Integration Guide

  docs:
  - about.md
  - contact-us.md
  - a-random-page.md
  - another-random-page.md